### ISSUE TITLE
[BUG] 404: /home/rootuser/.klsh/default: file not found

### ISSUE THREAD

**Issue by mmggg** [codingbunnys/klsh#11]
**Describe the bug**
When starting bash(i didn't use `setdefault` yet) i always get:
`/home/rootuser/.klsh/default: file not found`
**To Reproduce**
1. Make sure klsh isn't the default; if it is then run `unsetdefault`
2. Open a new bash window
3. See error

**Expected behavior**
The error message to disappear

**LOGS**
/home/rootuser/.klsh/default: file not found

**Product version (please complete the following information):**
 - Version [e.g. 1.0-beta.2]

**Additional context**
It's irritating

**Comment by codingbunnys** [comment]
hello, sorry but we will not fix this issue; as it is barely noticable

**Comment by mmggg** [comment]
okay

**Comment by codingbunnys** [comment]
shouldnt have closed it lol
