### ISSUE TITLE
[FEATURE] Individual files for installer to get instead of zip

### ISSUE THREAD

**Issue by LinuxCrafts** [codingbunnys/klsh#9]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
Make it so that instead of a zip for all the contents; you have a directory it grabs with all the contents, so that editing the program for pull requests is easier(viewing changes).

**Describe alternatives you've considered**
Unziping the file and then editing the individual files and finally reziping it

**Additional context**
None to be offered really

**Comment by codingbunnys** [comment]
This one will take longer to do. Please bare with me as i am one person doing this!

**Comment by codingbunnys** [comment]
Easy; lots of WGETs tho

**Comment by codingbunnys** [comment]
# PROGRESS:
have made a new installer that will fix this (installer is for the next version)
